require_relative '../../app/services/generate_maze_service.rb'
require_relative '../../app/services/solve_maze_service.rb'
require_relative '../spec_helper.rb'

RSpec.describe "Generating and solving a maze", type: :feature do
  it 'solves maze generated by recursive backfilling' do
    @maze = GenerateMazeService.new(width: 6, height: 6, seed: 42).call

    solving_service = SolveMazeService.new(maze: @maze, start: [0,0], finish: [5,5])

    expect(solving_service.call).to eq([
      [0, 0], [0, 0], [1, 0], [2, 0], [3, 0], [4, 0], [4, 1], [5, 1], [5, 2], [5, 3], [5, 4]
    ])
  end
end
